changesetBaseRefs:
  - develop
  - origin/develop

initFields:
  version: 0.0.1
  author-email: ""
  author-name: ""
  author-url: ""
  license: UNLICENSED
  private: true

nodeLinker: node-modules

preferInteractive: true
